// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnacxatschaawpjuypkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduYWN4YXRzY2hhYXdwanV5cGtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NjE4MDEsImV4cCI6MjA2ODEzNzgwMX0.41WZ4PJIWkk_6pORLGH-UkXRft3bzMs9E3ekPNIxymc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});